# Generated by Django 2.2.7 on 2019-11-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.CharField(default='', help_text='Date', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.CharField(default='', help_text='Latitude', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.CharField(default='', help_text='Longitude', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(default='', help_text='Shift', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(default='', help_text='Unique_Squirrel_ID', max_length=100),
        ),
    ]
