# Generated by Django 2.2.7 on 2019-12-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20191208_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.FloatField(default=0, help_text='Latitude'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.FloatField(default=0, help_text='Longitude'),
        ),
    ]
