# Generated by Django 2.2.7 on 2019-12-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0003_auto_20191208_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.CharField(default='', help_text='Latitude', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.CharField(default='', help_text='Longitude', max_length=100),
        ),
    ]
