# Generated by Django 2.2.7 on 2019-12-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0006_auto_20191208_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Other_Activities',
            field=models.CharField(default='', help_text='Other_Activities', max_length=100),
        ),
    ]
