# Generated by Django 2.2.7 on 2019-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0007_auto_20191208_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.CharField(default='', help_text='Date', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(default='', help_text='Unique_Squirrel_ID', max_length=100, primary_key=True, serialize=False),
        ),
    ]
